@apiUrl = http://localhost:5000

@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJsb3JlbnpvcHJvMzhAZ21haWwuY29tIiwiaWF0IjoxNzYzMTI0Mzk2LCJleHAiOjE3NjMxMjc5OTZ9.MGL4fXYFRQgCkCbLn7dANPnXUjnjzaC3RQzfY6pYDEk


### POST — Login utilisateur
POST {{apiUrl}}/auth/local
Content-Type: application/json

{
  "identifier": "lorenzopro38@gmail.com",
  "password": "LorenzoTest"
}

###
POST {{apiUrl}}/auth/local/register
Content-Type: application/json

{
  "username": "Lioxyze",
  "email": "lorenzopro38@gmail.com",
  "password": "LorenzoTest"

}


### GET ALL — Récupérer toutes les recettes
GET {{apiUrl}}/api/recettes
Content-Type: application/json
Authorization: Bearer {{token}}



###

### CREATE — Créer une recette
POST {{apiUrl}}/api/recettes
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "title": "Ratatouille provençale",
  "difficulty": 2,
  "budget": 1,
  "time": 40,
  "description": "Ratatouille traditionnelle du Sud."
}

###

### UPDATE — Mettre à jour une recette
PATCH {{apiUrl}}/api/recettes/4
Content-Type: application/json
Authorization: Bearer {{token}}


{
  "title": "Ratatouille maison",
  "difficulty": 3,
  "budget": 2,
  "time": 45,
  "description": "Version améliorée."
}

###

### DELETE — Supprimer une recette
DELETE {{apiUrl}}/api/recettes/1
Content-Type: application/json
Authorization: Bearer {{token}}

