@apiUrl = http://localhost:3001/api

###  Récupérer toutes les recettes
GET {{apiUrl}}/allRecipe
Content-Type: application/json

###

### Créer une recette
POST {{apiUrl}}/createRecipe
Content-Type: application/json

{
  "title": "Ratatouille provençale",
  "difficulty": "facile",
  "budget": "15€",
  "time": "40 min",
  "description": "Ratatouille traditionnelle du Sud."
}

###

###  Mettre à jour une recette
PATCH {{apiUrl}}/updateRecipe/1
Content-Type: application/json

{
  "title": "Ratatouille maison",
  "difficulty": "moyenne",
  "budget": "18€",
  "time": "45 min",
  "description": "Version améliorée de la ratatouille."
}

###

###  Supprimer une recette
DELETE {{apiUrl}}/deleteRecipe/1
Content-Type: application/json
